### PR TITLE
Issue #60: Add modes to also display checked-off items.

### PR DESCRIPTION
**Pull request by Naturjoghurt**
Add two new modes:
* Mode: First checklist (include completed)
* Mode: All steps (include completed)
In both modes the completed tasks stay on the card when marked as completed.

https://github.com/adrienjoly/chrome-next-step-for-trello/issues/60

### CODE REVIEW

**Comment by adrienjoly** [comment]
Hi @Naturjoghurt !

Congrats for your first pull request on Github, and thank you for having chosen to contribute to Next Step for Trello!

I'm reviewing your contribution right now, I'll let you know how it goes ^^

**Comment by adrienjoly** [comment]
Here are two screenshots of the new options, for the record:

screen shot 2018-01-19 at 21 26 43

screen shot 2018-01-19 at 21 27 20

**Comment by Naturjoghurt** [comment]
Hey @adrienjoly,
Thank you for your nice message, your fast response and the ideas on how to reduce complexity!
I reduced some complexity and the quantity of code already, if you have any other changes in mind that could help improving the code quality I am happy to hear them :+1:

**Comment by adrienjoly** [comment]
This update looks much better @Naturjoghurt , good job!

Sorry to bother, but [many lines](https://github.com/adrienjoly/chrome-next-step-for-trello/pull/63/files) were identified as "changed" because of changes of indentation...

Would you mind:
- restoring the 2-spaces indents we've been using in the main js file,
- making sure that your code editor / IDE does not change this style
- and they re-submit your PR so that only the lines of code you actually changes are displayed as changed?

Let me know if you need any assistance, or if you would like me to do it.

**Comment by Naturjoghurt** [comment]
Hey @adrienjoly,

I am sorry for messing with the indentation while refactoring, but I just missed that this was done automagically by my editor. I have undone all the indentation changes and syntax changes that should not be included in this change.

If you have any other ideas on how to improve this, just let me know and I will include them :)

**Comment by adrienjoly** [comment]
Looks much better, thanks!

Just a last note: may I ask why you moved the Announcement function, and the app state variables, please?

**Comment by adrienjoly** [comment]
PS: If you don't have time to revert these changes, please ask, @Naturjoghurt. I can do it for you. (unless they are really necessary, of course)

**Comment by adrienjoly** [comment]
Hi @Naturjoghurt, do you still want this PR merged? What's up?

**Comment by adrienjoly** [comment]
Thank you for your contribution, @Naturjoghurt ! 👏

**Pull request merged**
