### PR TITLE
Markdown formatting bugs

### PR DESCRIPTION
**Pull request by stevecshanks**
Splits Markdown rendering so that most Markdown does not affect code/URLs.

Unfortunately I can't seem to find a way to make this any simpler... but then I'm not much of a JavaScript developer!

I also have unit tests for the `renderMarkdown` function using Mocha/sinon-chrome/mock-browser.  Happy to submit those if too if they'd be useful - just let me know.

### CODE REVIEW

**Comment by adrienjoly** [comment]
Hi Steve! 

Thank you very much for your contribution!

Unfortunately, I'm not going to merge it as it, for the following reasons:
- you apparently removed support for hyperlinks,
- you're adding a lot of code that is hard for me to test without providing these tests.

=> Can you provide add your unit tests to this pull request, so that I can see the impact of your changes, please?

**Comment by stevecshanks** [comment]
Hi Adrien,

No problem!  I think I've spotted a bug anyway, so I'll take another look at this in the next few days.

**Comment by stevecshanks** [comment]
Hi Adrien,

I've updated with the test script I used, as well as tidying the code up and fixing a couple of bugs I noticed.

To run the tests, you should just need to run:

```
npm install .
npm test
```

I've also included some screenshots of the change:

Checklist on card view:

card

Before and after:

before_and_after

Any problems, just let me know!

Thanks,
Steve

**Comment by adrienjoly** [comment]
This is very good work, @stevecshanks! 🤘
Congrats, and thank you for your contribution! Especially for the automated tests!

**Comment by adrienjoly** [comment]
I took that opportunity to make Travis-CI run your tests automatically on every pushed commit :-)

**Comment by stevecshanks** [comment]
Thanks, really glad it was useful!

**Pull request merged**
