### PR TITLE
Fix updating cards

### LINKED ISSUE #54: Javascript error when updating a card with a checklist
I've noticed that when you update a card with a checklist (e.g. by ticking off an item or moving the card to a different list), the "next step" disappears and you get the following in the console log:

screen_shot_2017-07-03_at_14 20 11

I haven't dug into what might be causing this, but happy to take a look later this week if you'd like a second pair of eyes?

### PR DESCRIPTION
**Pull request by stevecshanks**
I haven't noticed any further problems, so I think this one is good to go!

Includes fixes for:

- Javascript error & card not updating when moving to a different list
- Card not updating when checklist item completed
- Card not updating if it has a cover image
- Card not updating if the "active-card" class is added to the end of the class list

Closes #54

### CODE REVIEW

**Comment by stevecshanks** [comment]
Hmmm, maybe not ready to go after all!  I'll review the Codacy issues and get back to you!

**Comment by adrienjoly** [comment]
Thank you Steve for your kind fix, and the excellent quality of your code, as always!

**Comment by stevecshanks** [comment]
Thank you :)  I get a lot of value out of this extension, so am always happy to help!

**Comment by adrienjoly** [comment]
🙌

I pushed v.1.8.12 (with you fix) on the Chrome Web Store, it should be updated within one hour.

**Pull request merged**
